# Generated by Django 2.0.1 on 2018-02-02 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0011_auto_20180131_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('day', models.CharField(choices=[('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday'), ('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('DAILY', 'Daily')], default='Daily', max_length=9)),
                ('hour', models.TimeField()),
                ('total_songs', models.IntegerField(default=1, verbose_name='total songs to beplayed')),
                ('active', models.BooleanField(default=True)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alarm_artist', to='library.Artist')),
                ('playlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alarm_playlist', to='library.Playlist')),
            ],
            options={
                'verbose_name_plural': 'ScheduledAlarms',
                'ordering': ('day',),
            },
        ),
        migrations.CreateModel(
            name='PlayedSongs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.DateTimeField(db_index=True, verbose_name='Song played time')),
                ('alarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='played_alarm', to='alarmclock.Alarms')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='played_song', to='library.Song')),
            ],
            options={
                'verbose_name_plural': 'PlayedSongs',
                'ordering': ('played',),
            },
        ),
        migrations.CreateModel(
            name='QueuedSongs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled', models.DateTimeField(auto_now_add=True)),
                ('played', models.BooleanField(default=False)),
                ('alarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queued_alarm', to='alarmclock.Alarms')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queued_song', to='library.Song')),
            ],
            options={
                'verbose_name_plural': 'QueuedSongs',
                'ordering': ('scheduled',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='alarms',
            unique_together={('day', 'hour')},
        ),
    ]
