# Generated by Django 2.0.1 on 2018-02-02 12:47

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('alarmclock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alarms',
            options={'ordering': ('day',), 'verbose_name_plural': 'Alarms'},
        ),
        migrations.AlterField(
            model_name='alarms',
            name='day',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday'), ('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('DAILY', 'Daily')], default='Daily', max_length=100),
        ),
    ]
