# Generated by Django 2.0.1 on 2018-02-02 15:16

import alarmclock.models
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('alarmclock', '0003_auto_20180202_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alarms',
            options={'ordering': ('updated',), 'verbose_name_plural': 'Alarms'},
        ),
        migrations.AlterField(
            model_name='alarms',
            name='day',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday'), ('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('DAILY', 'Daily')], default='Daily', max_length=100, validators=[alarmclock.models.validate_day]),
        ),
        migrations.AlterField(
            model_name='alarms',
            name='total_songs',
            field=models.IntegerField(default=1, verbose_name='total songs to be played'),
        ),
    ]
