# Generated by Django 2.0.1 on 2018-02-02 18:56

import alarmclock.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('alarmclock', '0005_auto_20180202_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarms',
            name='day',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday'), ('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('DAILY', 'Daily')], default='Daily', max_length=100),
        ),
        migrations.AlterField(
            model_name='alarms',
            name='name',
            field=models.CharField(max_length=30, unique=True, validators=[alarmclock.validators.validate_days]),
        ),
    ]
