# Generated by Django 2.0.1 on 2018-02-02 19:18

import alarmclock.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('alarmclock', '0006_auto_20180202_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarms',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alarm_artist', to='library.Artist', validators=[alarmclock.validators.validate_artist]),
        ),
        migrations.AlterField(
            model_name='alarms',
            name='day',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday'), ('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('DAILY', 'Daily')], default='Daily', max_length=100, validators=[alarmclock.validators.validate_days]),
        ),
        migrations.AlterField(
            model_name='alarms',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='alarms',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alarm_playlist', to='library.Playlist', validators=[alarmclock.validators.validate_playlist]),
        ),
    ]
