# Generated by Django 2.0.1 on 2018-02-05 21:02

import alarmclock.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('alarmclock', '0024_auto_20180202_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarms',
            name='daily',
            field=models.BooleanField(default=False, validators=[alarmclock.validators.validate_daily]),
        ),
        migrations.AlterField(
            model_name='alarms',
            name='day',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday'), ('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday')], max_length=100, null=True, validators=[alarmclock.validators.validate_days]),
        ),
    ]
