# Generated by Django 2.0.1 on 2018-02-07 20:44

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('alarmclock', '0025_auto_20180205_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarms',
            name='daily',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alarms',
            name='day',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday'), ('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday')], max_length=100, null=True),
        ),
    ]
