# Generated by Django 2.0.1 on 2018-02-07 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alarmclock', '0026_auto_20180207_2044'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alarms',
            unique_together={('daily', 'hour')},
        ),
    ]
