# Generated by Django 2.0.1 on 2018-02-13 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alarmclock', '0027_auto_20180207_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuedsongs',
            name='alarm',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queued_alarm', to='alarmclock.Alarms'),
        ),
    ]
