# Generated by Django 2.0.1 on 2018-02-19 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0011_auto_20180131_2123'),
        ('alarmclock', '0028_auto_20180213_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuedsongs',
            name='alarm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queued_alarm', to='alarmclock.Alarms'),
        ),
        migrations.AlterUniqueTogether(
            name='queuedsongs',
            unique_together={('alarm', 'song')},
        ),
    ]
