# Generated by Django 2.0.1 on 2018-02-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarmclock', '0029_auto_20180219_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='playedsongs',
            name='inserted',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='queuedsongs',
            name='played',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='queuedsongs',
            name='scheduled',
            field=models.DateTimeField(db_index=True),
        ),
    ]
