# Generated by Django 2.0.1 on 2018-02-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarmclock', '0030_auto_20180222_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playedsongs',
            name='inserted',
        ),
        migrations.AlterField(
            model_name='queuedsongs',
            name='played',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
