# Generated by Django 2.0.1 on 2018-02-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarmclock', '0032_auto_20180226_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuedsongs',
            name='played',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='Song played time'),
        ),
    ]
