# Generated by Django 2.0.1 on 2018-02-26 21:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alarmclock', '0033_auto_20180226_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='playedsongs',
            name='added',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now, verbose_name='when the song added here'),
            preserve_default=False,
        ),
    ]
