# Generated by Django 2.0.1 on 2018-02-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarmclock', '0034_playedsongs_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playedsongs',
            name='added',
            field=models.DateTimeField(auto_now=True, verbose_name='when the song added here'),
        ),
    ]
