# Generated by Django 2.0.3 on 2018-04-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarmclock', '0035_auto_20180226_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarms',
            name='executed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playedsongs',
            name='added',
            field=models.DateTimeField(auto_now=True, verbose_name='song added'),
        ),
    ]
