# Generated by Django 2.0.3 on 2018-04-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarmclock', '0039_auto_20180402_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarms',
            name='test',
        ),
        migrations.AlterField(
            model_name='alarms',
            name='executed',
            field=models.DateTimeField(db_index=True, default='2018-01-01 00:00:00'),
        ),
    ]
